### ISSUE TITLE
iOS 无法选择文本后播放

### ISSUE THREAD

**Issue by Nickilism** [BetterWorld-Liuser/autoMovies#1]
iOS 上选择文本后点播放无效果。
下面是用 AI 找到的解决办法，亲测有效：
Unfortunately, there is no direct way to get the selected text in Safari on iOS as it is not currently supported by the JavaScript API. However, you may try to implement a workaround by creating a custom selection mechanism within your web page. Here is an example of how you can achieve this:

```
document.addEventListener("touchstart", function(e) {
  // Initialize the start position of the touch
  var start = e.touches[0].clientX;

  document.addEventListener("touchend", function(e) {
    // Get the end position of the touch
    var end = e.changedTouches[0].clientX;

    // Check if the touch was a swipe
    if (start > end + 5) {
      // Get the selected text
      var selection = window.getSelection().toString();

      // Do something with the selected text
      console.log(selection);
    }
  });
});
```

In this example, we are using the `touchstart` and `touchend` events to detect a swipe gesture. When a swipe is detected, we use the `window.getSelection().toString()` method to get the selected text. Note that this will only work if the user swipes to select text within the web page.

**Comment by BetterWorld-Liuser** [comment]
牛，确实是我没测试到的地方，这就修复。谢谢

**Comment by BetterWorld-Liuser** [comment]
啊，我还想问一下，你在iOS端看的是哪部影片，因为我看手机端豆瓣通常都是不需要选择的，因为标题都是正常的不像电脑端豆瓣会夹杂外文。
