### ISSUE TITLE
播放按钮优化建议

### ISSUE THREAD

**Issue by Neoleex** [BetterWorld-Liuser/autoMovies#3]
## 希望能在播放按钮处加个按钮背景或者其他样式能够提亮播放
第一次使用时其实并没有发现播放按钮，因为以标题的样式展示确实有点不太显眼..（也或许我眼拙..）
后面又看了一遍文档才发现 标题旁边就是

**Comment by BetterWorld-Liuser** [comment]
好的

**Comment by BetterWorld-Liuser** [comment]
已优化为绿色，请更新最新版体验反馈。谢谢～
