### ISSUE TITLE
测速失败

### ISSUE THREAD

**Issue by yangliu-1995** [BetterWorld-Liuser/autoMovies#4]
你好，我是iOS平台一款支持油猴浏览器的开发者，在测试贵脚本的时候，发现测速这一个功能无法成功，想和你联系一下，解决我这边的兼容性问题，请问有联系方式吗？

**Comment by BetterWorld-Liuser** [comment]
微信：consistency_liu



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月18日(周六) 晚上10:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [BetterWorld-Liuser/autoMovies] 测速失败 (Issue #4)




 
你好，我是iOS平台一款支持油猴浏览器的开发者，在测试贵脚本的时候，发现测速这一个功能无法成功，想和你联系一下，解决我这边的兼容性问题，请问有联系方式吗？
